version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: kermartin
      POSTGRES_USER: kermartin
      POSTGRES_PASSWORD: kermartin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - kermartin_backend/.env
    environment:
      DJANGO_SETTINGS_MODULE: kermartin_backend.kermartin_project.settings
      DATABASE_URL: postgresql://kermartin:kermartin@db:5432/kermartin
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./kermartin_backend:/app
    command: bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: product/frontend
      dockerfile: Dockerfile.frontend
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./product/frontend:/app
    command: npm run dev -- --port 3000 --hostname 0.0.0.0
    depends_on:
      - backend

volumes:
  db_data:
