[tool.black]
line-length = 88
target-version = ["py312"]
extend-exclude = [
  "kermartin_backend/**/migrations/*",
  "kermartin_backend/staticfiles/*",
]

[tool.isort]
profile = "black"
line_length = 88
skip_glob = [
  "kermartin_backend/**/migrations/*",
  "kermartin_backend/staticfiles/*",
]
