# Generated by Django 5.2.4 on 2025-08-01 00:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=300)),
                ('numero_processo', models.CharField(blank=True, max_length=50)),
                ('tipo_crime', models.CharField(blank=True, choices=[('homicidio', 'Homicídio'), ('latrocinio', 'Latrocínio'), ('estupro', 'Estupro'), ('roubo', 'Roubo'), ('trafico', 'Tráfico de Drogas'), ('outros', 'Outros')], max_length=20)),
                ('comarca', models.CharField(blank=True, max_length=100)),
                ('vara', models.CharField(blank=True, max_length=100)),
                ('reu_nome', models.CharField(blank=True, max_length=200)),
                ('vitima_nome', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('analyzing', 'Em Análise'), ('completed', 'Concluído'), ('archived', 'Arquivado')], default='draft', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'db_table': 'processos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('arquivo_original', models.FileField(upload_to='documentos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('tipo_documento', models.CharField(choices=[('inquerito', 'Inquérito Policial'), ('denuncia', 'Denúncia'), ('resposta_acusacao', 'Resposta à Acusação'), ('sentencia_pronuncia', 'Sentença de Pronúncia'), ('alegacoes_finais', 'Alegações Finais'), ('ata_julgamento', 'Ata de Julgamento'), ('outros', 'Outros')], max_length=20)),
                ('texto_extraido', models.TextField(blank=True)),
                ('hash_arquivo', models.CharField(blank=True, max_length=64)),
                ('tamanho_arquivo', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.processo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessaoAnalise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modo_analise', models.CharField(choices=[('individual', 'Análise Individual'), ('completa', 'Análise Completa'), ('personalizada', 'Análise Personalizada')], max_length=20)),
                ('status', models.CharField(choices=[('iniciada', 'Iniciada'), ('em_progresso', 'Em Progresso'), ('concluida', 'Concluída'), ('erro', 'Erro'), ('cancelada', 'Cancelada')], default='iniciada', max_length=20)),
                ('bloco_atual', models.PositiveIntegerField(default=1)),
                ('subetapa_atual', models.PositiveIntegerField(default=1)),
                ('blocos_selecionados', models.JSONField(default=list)),
                ('configuracoes', models.JSONField(default=dict)),
                ('tempo_inicio', models.DateTimeField(auto_now_add=True)),
                ('tempo_fim', models.DateTimeField(blank=True, null=True)),
                ('tempo_total', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_analise', to='core.processo')),
            ],
            options={
                'verbose_name': 'Sessão de Análise',
                'verbose_name_plural': 'Sessões de Análise',
                'db_table': 'sessoes_analise',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('oab_numero', models.CharField(max_length=20, unique=True)),
                ('oab_estado', models.CharField(max_length=2)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('escritorio', models.CharField(blank=True, max_length=200)),
                ('especialidades', models.TextField(blank=True, help_text='Especialidades jurídicas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='processo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='core.usuario'),
        ),
        migrations.CreateModel(
            name='LogSeguranca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('login_sucesso', 'Login Bem-sucedido'), ('login_falha', 'Falha no Login'), ('prompt_injection', 'Tentativa de Prompt Injection'), ('upload_suspeito', 'Upload Suspeito'), ('acesso_negado', 'Acesso Negado'), ('erro_sistema', 'Erro do Sistema')], max_length=20)),
                ('descricao', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('dados_extras', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usuario')),
            ],
            options={
                'verbose_name': 'Log de Segurança',
                'verbose_name_plural': 'Logs de Segurança',
                'db_table': 'logs_seguranca',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoAnalise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bloco', models.PositiveIntegerField()),
                ('subetapa', models.PositiveIntegerField()),
                ('prompt_usado', models.TextField()),
                ('resposta_ia', models.TextField()),
                ('tokens_prompt', models.PositiveIntegerField(default=0)),
                ('tokens_resposta', models.PositiveIntegerField(default=0)),
                ('tokens_total', models.PositiveIntegerField(default=0)),
                ('tempo_processamento', models.FloatField(default=0.0)),
                ('modelo_usado', models.CharField(default='gpt-4-1106-preview', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='core.documento')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.sessaoanalise')),
            ],
            options={
                'verbose_name': 'Resultado de Análise',
                'verbose_name_plural': 'Resultados de Análise',
                'db_table': 'resultados_analise',
                'ordering': ['bloco', 'subetapa', '-created_at'],
                'unique_together': {('sessao', 'documento', 'bloco', 'subetapa')},
            },
        ),
    ]
