# Generated by Django 5.2.5 on 2025-08-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jurisprudencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("tribunal", models.CharField(blank=True, max_length=100, null=True)),
                ("data_julgamento", models.DateField(blank=True, null=True)),
                ("ementa", models.TextField(blank=True, null=True)),
                ("fundamentacao", models.TextField(blank=True, null=True)),
                ("pontos_estrategicos", models.TextField(blank=True, null=True)),
                ("teses_defensivas", models.TextField(blank=True, null=True)),
                ("tema", models.CharField(blank=True, max_length=100, null=True)),
                ("link", models.URLField(blank=True, max_length=500, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Jurisprudência",
                "verbose_name_plural": "Jurisprudências",
                "ordering": ["-data_julgamento", "-id"],
            },
        ),
    ]
