# Generated by Django 5.2.5 on 2025-08-10 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("juris", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JurisEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding", models.JSONField()),
                ("dim", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "jurisprudencia",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="juris.jurisprudencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Embedding de Jurisprudência",
                "verbose_name_plural": "Embeddings de Jurisprudência",
            },
        ),
    ]
