# Generated by Django 5.2.5 on 2025-08-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("juris", "0002_jurisembedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="jurisprudencia",
            name="dispositivos_citados",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="jurisprudencia",
            name="vinculante",
            field=models.BooleanField(default=False),
        ),
    ]
