# Generated by Django 5.2.5 on 2025-08-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("juris", "0003_jurisprudencia_dispositivos_citados_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jurisprudencia",
            name="bloco",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jurisprudencia",
            name="fase",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
