name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  backend:
    name: Backend (Django) tests + lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort flake8

      - name: Lint (flake8)
        run: flake8

      - name: Format check (black)
        run: black --check .

      - name: Import order check (isort)
        run: isort --check-only .

      - name: Run pytest
        env:
          DJANGO_SETTINGS_MODULE: kermartin_backend.kermartin_project.settings
          PYTHONPATH: .
          OPENAI_API_KEY: test-key
        run: pytest -q

  frontend:
    name: Frontend (Next.js) build + lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: product/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        env:
          NEXT_PUBLIC_API_BASE: http://127.0.0.1:8000
        run: npm run build
